/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateNewCollection {
  collectionTitle?: string;
  collectionDescription?: string;
  datasets?: {
    [k: string]: any;
  };
  [k: string]: any;
}
