/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FitnessEntry {
  '50m-sprint'?: any;
  'push-ups'?: any;
  benchpress?: any;
  squat?: any;
  [k: string]: any;
}
